- job_name: nodes-exporter
  scrape_interval: 5s
  basic_auth:
    username: node_exporter_user
    password: node_exporter_password
  ec2_sd_configs:
    - filters:
        - name: tag:Name
          values:
            - "polkadot-api*"
            - "substrate-sot"
  relabel_configs:
    - source_labels: [ '__meta_ec2_private_ip' ]
      target_label: '__address__'
      replacement: '$1:${node_exporter_port}'
- job_name: polkadot-library-nodes
  scrape_interval: 5s
  ec2_sd_configs:
    - filters:
        - name: tag:Name
          values:
            - "polkadot-api*"
  relabel_configs:
    - source_labels: [ '__meta_ec2_private_ip' ]
      target_label: '__address__'
      replacement: '$1:${polkadot_prometheus_port}'
- job_name: kusama-library-nodes
  scrape_interval: 5s
  ec2_sd_configs:
    - filters:
        - name: tag:Name
          values:
            - "polkadot-api*"
  relabel_configs:
    - source_labels: [ '__meta_ec2_private_ip' ]
      target_label: '__address__'
      replacement: '$1:${kusama_prometheus_port}'
- job_name: polkadot-truth-nodes
  scrape_interval: 5s
  ec2_sd_configs:
    - filters:
        - name: tag:Name
          values:
            - "substrate-sot"
  relabel_configs:
    - source_labels: [ '__meta_ec2_private_ip' ]
      target_label: '__address__'
      replacement: '$1:${polkadot_prometheus_port}'
- job_name: kusama-truth-nodes
  scrape_interval: 5s
  ec2_sd_configs:
    - filters:
        - name: tag:Name
          values:
            - "substrate-sot"
  relabel_configs:
    - source_labels: [ '__meta_ec2_private_ip' ]
      target_label: '__address__'
      replacement: '$1:${kusama_prometheus_port}'

- job_name: cloudwatch
  scrape_interval: 10s
  metrics_path: '/metrics'
  kubernetes_sd_configs:
    - role: pod
      selectors:
        - role: pod
          label: "app=prometheus-cloudwatch-exporter"
